<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Capillary.ShellProxy.Model\Capillary.ShellProxy.Model.csproj" />
    <ProjectReference Include="..\Capillary.ShellProxy.Utilities\Capillary.ShellProxy.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.105.7"/>
    <PackageReference Include="AWSSDK.DynamoDBV2" Version="3.5.0.2" />
    <PackageReference Include="AWSSDK.S3" Version="3.5.0.2" />
    <PackageReference Include="System.Runtime.Extensions" Version="4.3.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>
